"""add slug to Blog

Revision ID: 860ab7e4f615
Revises: 5530bd18c5aa
Create Date: 2025-07-29 14:58:34.587204

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '860ab7e4f615'
down_revision: Union[str, Sequence[str], None] = '5530bd18c5aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('slug', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'blogs', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='unique')
    op.drop_column('blogs', 'slug')
    # ### end Alembic commands ###
