"""Add is_deleted field to blogs

Revision ID: 8d6011f0ef9a
Revises: 860ab7e4f615
Create Date: 2025-07-30 14:39:20.906747

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '8d6011f0ef9a'
down_revision: Union[str, Sequence[str], None] = '860ab7e4f615'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.add_column(
        'blogs',
        sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default=sa.text('false'))
    )
    op.alter_column('blogs', 'is_deleted', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'is_deleted')
    # ### end Alembic commands ###
